[app_conf]
  h5_user_bag_page = "https://testboc.inke.cn:818/innerapp/virtual-props-shop/packet/index.html"
  source_type = 9999
  source_type_key = "cd372d198f0c7b7eb773049ba67c09c1"
  system_uid = 181918

[[database]]
  master = "root:root@tcp(127.0.0.1:32786)/shopping_store?loc=Local&parseTime=true&charset=utf8"
  name = "busi.privilege.new_shopping-mysql"
  slaves = ["root:root@tcp(127.0.0.1:32786)/shopping_store?loc=Local&parseTime=true&charset=utf8"]

[[kafka_producer_client]]
  get_error = true
  get_success = true
  kafka_broken = "127.0.0.1:32789"
  producer_to = "busi.privilege.new_shopping-kafka"
  required_acks = "WaitForAll"
  retrymax = 1
  topic = ""
  use_sync = true

[[kafka_producer_client]]
  get_error = true
  get_success = true
  kafka_broken = "127.0.0.1:32789"
  producer_to = "busi.privilege.new_shopping-kafka"
  required_acks = "WaitForAll"
  retrymax = 1
  topic = "a"
  use_sync = true

[log]
  level = "debug"
  logpath = "logs"
  rotate = "hour"
  succ_stat_code = [499, 780, 781, 782]

[[redis]]
  addr = "127.0.0.1:32788"
  connect_timeout = 100
  database = 0
  idle_timeout = 6000
  max_active = 500
  max_idle = 100
  password = ""
  read_timeout = 100
  retry = 0
  server_name = "busi.privilege.new_shopping-redis"
  slow_time = 200
  write_timeout = 100

[server]
  port = 9098
  service_name = "busi.privilege.new_shopping"

[[server_client]]
  balancetype = "roundrobin"
  endpoints = "10.55.3.195:8089"
  proto = "http"
  read_timeout = 200
  retry_times = 0
  service_name = "user.profile.gateway"
  slow_time = 200

[[server_client]]
  balancetype = "roundrobin"
  endpoints = "ali-a-cbc-testing01.bj:10000"
  proto = "http"
  read_timeout = 200
  retry_times = 1
  service_name = "busi.privilege.user_bag"
  slow_time = 200

[[server_client]]
  balancetype = "roundrobin"
  endpoints = "10.55.3.195:22582"
  proto = "http"
  read_timeout = 200
  retry_times = 0
  service_name = "user.message.logic"
  slow_time = 200

[thrift]
  host = "10.55.3.192"
  idle_timeout = 1000
  initial_cap = 12
  max_cap = 12
  port = "2060"
