

[[server_client]]
service_name="servicehttp"
proto="http"
endpoints="116.211.167.106:80,127.0.0.1:7832"
balancetype="random"
read_timeout=3000
retry_times = 1

[[server_client]]
service_name="servicerpc"
proto="rpc"
endpoints="127.0.0.1:6271,127.0.0.1:7271"
balancetype="roundrobin"
connnect_timeout=1100
read_timeout=1000
write_timeout=1110
max_idleconn = 50
	
