// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.center.base.proto

package game_center_base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	proxy "github.com/lfxnxf/frame/logic/inits/proxy"
	client "github.com/lfxnxf/frame/logic/inits/rpc/client"
	server "github.com/lfxnxf/frame/logic/inits/rpc/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvitationEmptyResp struct {
	DmError              int64    `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvitationEmptyResp) Reset()         { *m = InvitationEmptyResp{} }
func (m *InvitationEmptyResp) String() string { return proto.CompactTextString(m) }
func (*InvitationEmptyResp) ProtoMessage()    {}
func (*InvitationEmptyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{0}
}

func (m *InvitationEmptyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationEmptyResp.Unmarshal(m, b)
}
func (m *InvitationEmptyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationEmptyResp.Marshal(b, m, deterministic)
}
func (m *InvitationEmptyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationEmptyResp.Merge(m, src)
}
func (m *InvitationEmptyResp) XXX_Size() int {
	return xxx_messageInfo_InvitationEmptyResp.Size(m)
}
func (m *InvitationEmptyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationEmptyResp.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationEmptyResp proto.InternalMessageInfo

func (m *InvitationEmptyResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *InvitationEmptyResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type InvitationIdResp struct {
	DmError              int64                  `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data                 *InvitationIdResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *InvitationIdResp) Reset()         { *m = InvitationIdResp{} }
func (m *InvitationIdResp) String() string { return proto.CompactTextString(m) }
func (*InvitationIdResp) ProtoMessage()    {}
func (*InvitationIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{1}
}

func (m *InvitationIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationIdResp.Unmarshal(m, b)
}
func (m *InvitationIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationIdResp.Marshal(b, m, deterministic)
}
func (m *InvitationIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationIdResp.Merge(m, src)
}
func (m *InvitationIdResp) XXX_Size() int {
	return xxx_messageInfo_InvitationIdResp.Size(m)
}
func (m *InvitationIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationIdResp proto.InternalMessageInfo

func (m *InvitationIdResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *InvitationIdResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *InvitationIdResp) GetData() *InvitationIdResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type InvitationIdResp_Data struct {
	InvitationId         string   `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvitationIdResp_Data) Reset()         { *m = InvitationIdResp_Data{} }
func (m *InvitationIdResp_Data) String() string { return proto.CompactTextString(m) }
func (*InvitationIdResp_Data) ProtoMessage()    {}
func (*InvitationIdResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{1, 0}
}

func (m *InvitationIdResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationIdResp_Data.Unmarshal(m, b)
}
func (m *InvitationIdResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationIdResp_Data.Marshal(b, m, deterministic)
}
func (m *InvitationIdResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationIdResp_Data.Merge(m, src)
}
func (m *InvitationIdResp_Data) XXX_Size() int {
	return xxx_messageInfo_InvitationIdResp_Data.Size(m)
}
func (m *InvitationIdResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationIdResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationIdResp_Data proto.InternalMessageInfo

func (m *InvitationIdResp_Data) GetInvitationId() string {
	if m != nil {
		return m.InvitationId
	}
	return ""
}

type SetInvitationInfoReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetUid            int64    `protobuf:"varint,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	GameType             int64    `protobuf:"varint,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	GameMode             int64    `protobuf:"varint,4,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	Source               int64    `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	RoomId               string   `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetInvitationInfoReq) Reset()         { *m = SetInvitationInfoReq{} }
func (m *SetInvitationInfoReq) String() string { return proto.CompactTextString(m) }
func (*SetInvitationInfoReq) ProtoMessage()    {}
func (*SetInvitationInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{2}
}

func (m *SetInvitationInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetInvitationInfoReq.Unmarshal(m, b)
}
func (m *SetInvitationInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetInvitationInfoReq.Marshal(b, m, deterministic)
}
func (m *SetInvitationInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetInvitationInfoReq.Merge(m, src)
}
func (m *SetInvitationInfoReq) XXX_Size() int {
	return xxx_messageInfo_SetInvitationInfoReq.Size(m)
}
func (m *SetInvitationInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetInvitationInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetInvitationInfoReq proto.InternalMessageInfo

func (m *SetInvitationInfoReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SetInvitationInfoReq) GetTargetUid() int64 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

func (m *SetInvitationInfoReq) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *SetInvitationInfoReq) GetGameMode() int64 {
	if m != nil {
		return m.GameMode
	}
	return 0
}

func (m *SetInvitationInfoReq) GetSource() int64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *SetInvitationInfoReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type InvitationIdReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	InvitationId         string   `protobuf:"bytes,2,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvitationIdReq) Reset()         { *m = InvitationIdReq{} }
func (m *InvitationIdReq) String() string { return proto.CompactTextString(m) }
func (*InvitationIdReq) ProtoMessage()    {}
func (*InvitationIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{3}
}

func (m *InvitationIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationIdReq.Unmarshal(m, b)
}
func (m *InvitationIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationIdReq.Marshal(b, m, deterministic)
}
func (m *InvitationIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationIdReq.Merge(m, src)
}
func (m *InvitationIdReq) XXX_Size() int {
	return xxx_messageInfo_InvitationIdReq.Size(m)
}
func (m *InvitationIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationIdReq proto.InternalMessageInfo

func (m *InvitationIdReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InvitationIdReq) GetInvitationId() string {
	if m != nil {
		return m.InvitationId
	}
	return ""
}

type UidReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidReq) Reset()         { *m = UidReq{} }
func (m *UidReq) String() string { return proto.CompactTextString(m) }
func (*UidReq) ProtoMessage()    {}
func (*UidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{4}
}

func (m *UidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidReq.Unmarshal(m, b)
}
func (m *UidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidReq.Marshal(b, m, deterministic)
}
func (m *UidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidReq.Merge(m, src)
}
func (m *UidReq) XXX_Size() int {
	return xxx_messageInfo_UidReq.Size(m)
}
func (m *UidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UidReq.DiscardUnknown(m)
}

var xxx_messageInfo_UidReq proto.InternalMessageInfo

func (m *UidReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type DontDisturbStatus struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DontDisturbStatus) Reset()         { *m = DontDisturbStatus{} }
func (m *DontDisturbStatus) String() string { return proto.CompactTextString(m) }
func (*DontDisturbStatus) ProtoMessage()    {}
func (*DontDisturbStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{5}
}

func (m *DontDisturbStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DontDisturbStatus.Unmarshal(m, b)
}
func (m *DontDisturbStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DontDisturbStatus.Marshal(b, m, deterministic)
}
func (m *DontDisturbStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DontDisturbStatus.Merge(m, src)
}
func (m *DontDisturbStatus) XXX_Size() int {
	return xxx_messageInfo_DontDisturbStatus.Size(m)
}
func (m *DontDisturbStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DontDisturbStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DontDisturbStatus proto.InternalMessageInfo

func (m *DontDisturbStatus) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GetInvitationInfoResp struct {
	DmError              int64               `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string              `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data                 *InvitationInfoData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetInvitationInfoResp) Reset()         { *m = GetInvitationInfoResp{} }
func (m *GetInvitationInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetInvitationInfoResp) ProtoMessage()    {}
func (*GetInvitationInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{6}
}

func (m *GetInvitationInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvitationInfoResp.Unmarshal(m, b)
}
func (m *GetInvitationInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvitationInfoResp.Marshal(b, m, deterministic)
}
func (m *GetInvitationInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvitationInfoResp.Merge(m, src)
}
func (m *GetInvitationInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetInvitationInfoResp.Size(m)
}
func (m *GetInvitationInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvitationInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvitationInfoResp proto.InternalMessageInfo

func (m *GetInvitationInfoResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *GetInvitationInfoResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *GetInvitationInfoResp) GetData() *InvitationInfoData {
	if m != nil {
		return m.Data
	}
	return nil
}

type InvitationInfoData struct {
	InvitationId         string    `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	Sender               int64     `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receive              int64     `protobuf:"varint,3,opt,name=receive,proto3" json:"receive,omitempty"`
	GameInfo             *GameInfo `protobuf:"bytes,4,opt,name=game_info,json=gameInfo,proto3" json:"game_info,omitempty"`
	CreateAt             int64     `protobuf:"varint,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Status               int64     `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	RoomId               string    `protobuf:"bytes,7,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Source               int64     `protobuf:"varint,8,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InvitationInfoData) Reset()         { *m = InvitationInfoData{} }
func (m *InvitationInfoData) String() string { return proto.CompactTextString(m) }
func (*InvitationInfoData) ProtoMessage()    {}
func (*InvitationInfoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{7}
}

func (m *InvitationInfoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationInfoData.Unmarshal(m, b)
}
func (m *InvitationInfoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationInfoData.Marshal(b, m, deterministic)
}
func (m *InvitationInfoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationInfoData.Merge(m, src)
}
func (m *InvitationInfoData) XXX_Size() int {
	return xxx_messageInfo_InvitationInfoData.Size(m)
}
func (m *InvitationInfoData) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationInfoData.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationInfoData proto.InternalMessageInfo

func (m *InvitationInfoData) GetInvitationId() string {
	if m != nil {
		return m.InvitationId
	}
	return ""
}

func (m *InvitationInfoData) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *InvitationInfoData) GetReceive() int64 {
	if m != nil {
		return m.Receive
	}
	return 0
}

func (m *InvitationInfoData) GetGameInfo() *GameInfo {
	if m != nil {
		return m.GameInfo
	}
	return nil
}

func (m *InvitationInfoData) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *InvitationInfoData) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InvitationInfoData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *InvitationInfoData) GetSource() int64 {
	if m != nil {
		return m.Source
	}
	return 0
}

type UserInfo struct {
	Nick                 string   `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Portrait             string   `protobuf:"bytes,2,opt,name=portrait,proto3" json:"portrait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{8}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *UserInfo) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

type GameInfo struct {
	GameName             string   `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	GameModeText         string   `protobuf:"bytes,2,opt,name=game_mode_text,json=gameModeText,proto3" json:"game_mode_text,omitempty"`
	GameType             int64    `protobuf:"varint,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	GameMode             int64    `protobuf:"varint,4,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	GameIcon             string   `protobuf:"bytes,5,opt,name=game_icon,json=gameIcon,proto3" json:"game_icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameInfo) Reset()         { *m = GameInfo{} }
func (m *GameInfo) String() string { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()    {}
func (*GameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{9}
}

func (m *GameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfo.Unmarshal(m, b)
}
func (m *GameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfo.Marshal(b, m, deterministic)
}
func (m *GameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfo.Merge(m, src)
}
func (m *GameInfo) XXX_Size() int {
	return xxx_messageInfo_GameInfo.Size(m)
}
func (m *GameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfo proto.InternalMessageInfo

func (m *GameInfo) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *GameInfo) GetGameModeText() string {
	if m != nil {
		return m.GameModeText
	}
	return ""
}

func (m *GameInfo) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GameInfo) GetGameMode() int64 {
	if m != nil {
		return m.GameMode
	}
	return 0
}

func (m *GameInfo) GetGameIcon() string {
	if m != nil {
		return m.GameIcon
	}
	return ""
}

type InvitationFreqSingleReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetUid            int64    `protobuf:"varint,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvitationFreqSingleReq) Reset()         { *m = InvitationFreqSingleReq{} }
func (m *InvitationFreqSingleReq) String() string { return proto.CompactTextString(m) }
func (*InvitationFreqSingleReq) ProtoMessage()    {}
func (*InvitationFreqSingleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{10}
}

func (m *InvitationFreqSingleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationFreqSingleReq.Unmarshal(m, b)
}
func (m *InvitationFreqSingleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationFreqSingleReq.Marshal(b, m, deterministic)
}
func (m *InvitationFreqSingleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationFreqSingleReq.Merge(m, src)
}
func (m *InvitationFreqSingleReq) XXX_Size() int {
	return xxx_messageInfo_InvitationFreqSingleReq.Size(m)
}
func (m *InvitationFreqSingleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationFreqSingleReq.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationFreqSingleReq proto.InternalMessageInfo

func (m *InvitationFreqSingleReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InvitationFreqSingleReq) GetTargetUid() int64 {
	if m != nil {
		return m.TargetUid
	}
	return 0
}

type InvitationFreqSingleResp struct {
	DmError              int64                          `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string                         `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data                 *InvitationFreqSingleResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *InvitationFreqSingleResp) Reset()         { *m = InvitationFreqSingleResp{} }
func (m *InvitationFreqSingleResp) String() string { return proto.CompactTextString(m) }
func (*InvitationFreqSingleResp) ProtoMessage()    {}
func (*InvitationFreqSingleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{11}
}

func (m *InvitationFreqSingleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationFreqSingleResp.Unmarshal(m, b)
}
func (m *InvitationFreqSingleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationFreqSingleResp.Marshal(b, m, deterministic)
}
func (m *InvitationFreqSingleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationFreqSingleResp.Merge(m, src)
}
func (m *InvitationFreqSingleResp) XXX_Size() int {
	return xxx_messageInfo_InvitationFreqSingleResp.Size(m)
}
func (m *InvitationFreqSingleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationFreqSingleResp.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationFreqSingleResp proto.InternalMessageInfo

func (m *InvitationFreqSingleResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *InvitationFreqSingleResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *InvitationFreqSingleResp) GetData() *InvitationFreqSingleResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type InvitationFreqSingleResp_Data struct {
	RemainingTime        int64    `protobuf:"varint,1,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
	IsCan                bool     `protobuf:"varint,2,opt,name=is_can,json=isCan,proto3" json:"is_can,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvitationFreqSingleResp_Data) Reset()         { *m = InvitationFreqSingleResp_Data{} }
func (m *InvitationFreqSingleResp_Data) String() string { return proto.CompactTextString(m) }
func (*InvitationFreqSingleResp_Data) ProtoMessage()    {}
func (*InvitationFreqSingleResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{11, 0}
}

func (m *InvitationFreqSingleResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvitationFreqSingleResp_Data.Unmarshal(m, b)
}
func (m *InvitationFreqSingleResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvitationFreqSingleResp_Data.Marshal(b, m, deterministic)
}
func (m *InvitationFreqSingleResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvitationFreqSingleResp_Data.Merge(m, src)
}
func (m *InvitationFreqSingleResp_Data) XXX_Size() int {
	return xxx_messageInfo_InvitationFreqSingleResp_Data.Size(m)
}
func (m *InvitationFreqSingleResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_InvitationFreqSingleResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_InvitationFreqSingleResp_Data proto.InternalMessageInfo

func (m *InvitationFreqSingleResp_Data) GetRemainingTime() int64 {
	if m != nil {
		return m.RemainingTime
	}
	return 0
}

func (m *InvitationFreqSingleResp_Data) GetIsCan() bool {
	if m != nil {
		return m.IsCan
	}
	return false
}

type SetContinuousRefusedReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetContinuousRefusedReq) Reset()         { *m = SetContinuousRefusedReq{} }
func (m *SetContinuousRefusedReq) String() string { return proto.CompactTextString(m) }
func (*SetContinuousRefusedReq) ProtoMessage()    {}
func (*SetContinuousRefusedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{12}
}

func (m *SetContinuousRefusedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetContinuousRefusedReq.Unmarshal(m, b)
}
func (m *SetContinuousRefusedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetContinuousRefusedReq.Marshal(b, m, deterministic)
}
func (m *SetContinuousRefusedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetContinuousRefusedReq.Merge(m, src)
}
func (m *SetContinuousRefusedReq) XXX_Size() int {
	return xxx_messageInfo_SetContinuousRefusedReq.Size(m)
}
func (m *SetContinuousRefusedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetContinuousRefusedReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetContinuousRefusedReq proto.InternalMessageInfo

func (m *SetContinuousRefusedReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SetContinuousRefusedReq) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ContinuousRefusedResp struct {
	DmError              int64                       `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string                      `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data                 *ContinuousRefusedResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ContinuousRefusedResp) Reset()         { *m = ContinuousRefusedResp{} }
func (m *ContinuousRefusedResp) String() string { return proto.CompactTextString(m) }
func (*ContinuousRefusedResp) ProtoMessage()    {}
func (*ContinuousRefusedResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{13}
}

func (m *ContinuousRefusedResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContinuousRefusedResp.Unmarshal(m, b)
}
func (m *ContinuousRefusedResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContinuousRefusedResp.Marshal(b, m, deterministic)
}
func (m *ContinuousRefusedResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinuousRefusedResp.Merge(m, src)
}
func (m *ContinuousRefusedResp) XXX_Size() int {
	return xxx_messageInfo_ContinuousRefusedResp.Size(m)
}
func (m *ContinuousRefusedResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinuousRefusedResp.DiscardUnknown(m)
}

var xxx_messageInfo_ContinuousRefusedResp proto.InternalMessageInfo

func (m *ContinuousRefusedResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *ContinuousRefusedResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *ContinuousRefusedResp) GetData() *ContinuousRefusedResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ContinuousRefusedResp_Data struct {
	IsShowDontDis        int64    `protobuf:"varint,1,opt,name=is_show_dont_dis,json=isShowDontDis,proto3" json:"is_show_dont_dis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContinuousRefusedResp_Data) Reset()         { *m = ContinuousRefusedResp_Data{} }
func (m *ContinuousRefusedResp_Data) String() string { return proto.CompactTextString(m) }
func (*ContinuousRefusedResp_Data) ProtoMessage()    {}
func (*ContinuousRefusedResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{13, 0}
}

func (m *ContinuousRefusedResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContinuousRefusedResp_Data.Unmarshal(m, b)
}
func (m *ContinuousRefusedResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContinuousRefusedResp_Data.Marshal(b, m, deterministic)
}
func (m *ContinuousRefusedResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinuousRefusedResp_Data.Merge(m, src)
}
func (m *ContinuousRefusedResp_Data) XXX_Size() int {
	return xxx_messageInfo_ContinuousRefusedResp_Data.Size(m)
}
func (m *ContinuousRefusedResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinuousRefusedResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ContinuousRefusedResp_Data proto.InternalMessageInfo

func (m *ContinuousRefusedResp_Data) GetIsShowDontDis() int64 {
	if m != nil {
		return m.IsShowDontDis
	}
	return 0
}

type SetInvitationRoomIdReq struct {
	InvitationId         string   `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetInvitationRoomIdReq) Reset()         { *m = SetInvitationRoomIdReq{} }
func (m *SetInvitationRoomIdReq) String() string { return proto.CompactTextString(m) }
func (*SetInvitationRoomIdReq) ProtoMessage()    {}
func (*SetInvitationRoomIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{14}
}

func (m *SetInvitationRoomIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetInvitationRoomIdReq.Unmarshal(m, b)
}
func (m *SetInvitationRoomIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetInvitationRoomIdReq.Marshal(b, m, deterministic)
}
func (m *SetInvitationRoomIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetInvitationRoomIdReq.Merge(m, src)
}
func (m *SetInvitationRoomIdReq) XXX_Size() int {
	return xxx_messageInfo_SetInvitationRoomIdReq.Size(m)
}
func (m *SetInvitationRoomIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetInvitationRoomIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetInvitationRoomIdReq proto.InternalMessageInfo

func (m *SetInvitationRoomIdReq) GetInvitationId() string {
	if m != nil {
		return m.InvitationId
	}
	return ""
}

func (m *SetInvitationRoomIdReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

// 用户战绩更新
type UpdateUserGameRecordReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameType             int64    `protobuf:"varint,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	GameMode             int64    `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	GameResult           int64    `protobuf:"varint,4,opt,name=game_result,json=gameResult,proto3" json:"game_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserGameRecordReq) Reset()         { *m = UpdateUserGameRecordReq{} }
func (m *UpdateUserGameRecordReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserGameRecordReq) ProtoMessage()    {}
func (*UpdateUserGameRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{15}
}

func (m *UpdateUserGameRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserGameRecordReq.Unmarshal(m, b)
}
func (m *UpdateUserGameRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserGameRecordReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserGameRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserGameRecordReq.Merge(m, src)
}
func (m *UpdateUserGameRecordReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserGameRecordReq.Size(m)
}
func (m *UpdateUserGameRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserGameRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserGameRecordReq proto.InternalMessageInfo

func (m *UpdateUserGameRecordReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UpdateUserGameRecordReq) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *UpdateUserGameRecordReq) GetGameMode() int64 {
	if m != nil {
		return m.GameMode
	}
	return 0
}

func (m *UpdateUserGameRecordReq) GetGameResult() int64 {
	if m != nil {
		return m.GameResult
	}
	return 0
}

type UpdateUserGameRecordResp struct {
	DmError              int64    `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserGameRecordResp) Reset()         { *m = UpdateUserGameRecordResp{} }
func (m *UpdateUserGameRecordResp) String() string { return proto.CompactTextString(m) }
func (*UpdateUserGameRecordResp) ProtoMessage()    {}
func (*UpdateUserGameRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{16}
}

func (m *UpdateUserGameRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserGameRecordResp.Unmarshal(m, b)
}
func (m *UpdateUserGameRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserGameRecordResp.Marshal(b, m, deterministic)
}
func (m *UpdateUserGameRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserGameRecordResp.Merge(m, src)
}
func (m *UpdateUserGameRecordResp) XXX_Size() int {
	return xxx_messageInfo_UpdateUserGameRecordResp.Size(m)
}
func (m *UpdateUserGameRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserGameRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserGameRecordResp proto.InternalMessageInfo

func (m *UpdateUserGameRecordResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *UpdateUserGameRecordResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

// 批量用户战绩更新
type BatchUpdateUserGameRecordReq struct {
	GameRecords          []*UpdateUserGameRecordReq `protobuf:"bytes,1,rep,name=game_records,json=gameRecords,proto3" json:"game_records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BatchUpdateUserGameRecordReq) Reset()         { *m = BatchUpdateUserGameRecordReq{} }
func (m *BatchUpdateUserGameRecordReq) String() string { return proto.CompactTextString(m) }
func (*BatchUpdateUserGameRecordReq) ProtoMessage()    {}
func (*BatchUpdateUserGameRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{17}
}

func (m *BatchUpdateUserGameRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchUpdateUserGameRecordReq.Unmarshal(m, b)
}
func (m *BatchUpdateUserGameRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchUpdateUserGameRecordReq.Marshal(b, m, deterministic)
}
func (m *BatchUpdateUserGameRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUpdateUserGameRecordReq.Merge(m, src)
}
func (m *BatchUpdateUserGameRecordReq) XXX_Size() int {
	return xxx_messageInfo_BatchUpdateUserGameRecordReq.Size(m)
}
func (m *BatchUpdateUserGameRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUpdateUserGameRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUpdateUserGameRecordReq proto.InternalMessageInfo

func (m *BatchUpdateUserGameRecordReq) GetGameRecords() []*UpdateUserGameRecordReq {
	if m != nil {
		return m.GameRecords
	}
	return nil
}

type BatchUpdateUserGameRecordResp struct {
	DmError              int64    `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchUpdateUserGameRecordResp) Reset()         { *m = BatchUpdateUserGameRecordResp{} }
func (m *BatchUpdateUserGameRecordResp) String() string { return proto.CompactTextString(m) }
func (*BatchUpdateUserGameRecordResp) ProtoMessage()    {}
func (*BatchUpdateUserGameRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{18}
}

func (m *BatchUpdateUserGameRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchUpdateUserGameRecordResp.Unmarshal(m, b)
}
func (m *BatchUpdateUserGameRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchUpdateUserGameRecordResp.Marshal(b, m, deterministic)
}
func (m *BatchUpdateUserGameRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUpdateUserGameRecordResp.Merge(m, src)
}
func (m *BatchUpdateUserGameRecordResp) XXX_Size() int {
	return xxx_messageInfo_BatchUpdateUserGameRecordResp.Size(m)
}
func (m *BatchUpdateUserGameRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUpdateUserGameRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUpdateUserGameRecordResp proto.InternalMessageInfo

func (m *BatchUpdateUserGameRecordResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *BatchUpdateUserGameRecordResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

// 用户战绩查询
type GetUserGameRecordReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameType             int64    `protobuf:"varint,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	GameMode             int64    `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	Begin                int64    `protobuf:"varint,4,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64    `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserGameRecordReq) Reset()         { *m = GetUserGameRecordReq{} }
func (m *GetUserGameRecordReq) String() string { return proto.CompactTextString(m) }
func (*GetUserGameRecordReq) ProtoMessage()    {}
func (*GetUserGameRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{19}
}

func (m *GetUserGameRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGameRecordReq.Unmarshal(m, b)
}
func (m *GetUserGameRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGameRecordReq.Marshal(b, m, deterministic)
}
func (m *GetUserGameRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGameRecordReq.Merge(m, src)
}
func (m *GetUserGameRecordReq) XXX_Size() int {
	return xxx_messageInfo_GetUserGameRecordReq.Size(m)
}
func (m *GetUserGameRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGameRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGameRecordReq proto.InternalMessageInfo

func (m *GetUserGameRecordReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetUserGameRecordReq) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GetUserGameRecordReq) GetGameMode() int64 {
	if m != nil {
		return m.GameMode
	}
	return 0
}

func (m *GetUserGameRecordReq) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *GetUserGameRecordReq) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type GetUserGameRecordResp struct {
	DmError              int64                       `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string                      `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data                 *GetUserGameRecordResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetUserGameRecordResp) Reset()         { *m = GetUserGameRecordResp{} }
func (m *GetUserGameRecordResp) String() string { return proto.CompactTextString(m) }
func (*GetUserGameRecordResp) ProtoMessage()    {}
func (*GetUserGameRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{20}
}

func (m *GetUserGameRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGameRecordResp.Unmarshal(m, b)
}
func (m *GetUserGameRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGameRecordResp.Marshal(b, m, deterministic)
}
func (m *GetUserGameRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGameRecordResp.Merge(m, src)
}
func (m *GetUserGameRecordResp) XXX_Size() int {
	return xxx_messageInfo_GetUserGameRecordResp.Size(m)
}
func (m *GetUserGameRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGameRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGameRecordResp proto.InternalMessageInfo

func (m *GetUserGameRecordResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *GetUserGameRecordResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *GetUserGameRecordResp) GetData() *GetUserGameRecordResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetUserGameRecordResp_UserGameRecord struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameType             int64    `protobuf:"varint,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	GameMode             int64    `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	WonTimes             int64    `protobuf:"varint,4,opt,name=won_times,json=wonTimes,proto3" json:"won_times,omitempty"`
	LoseTimes            int64    `protobuf:"varint,5,opt,name=lose_times,json=loseTimes,proto3" json:"lose_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserGameRecordResp_UserGameRecord) Reset()         { *m = GetUserGameRecordResp_UserGameRecord{} }
func (m *GetUserGameRecordResp_UserGameRecord) String() string { return proto.CompactTextString(m) }
func (*GetUserGameRecordResp_UserGameRecord) ProtoMessage()    {}
func (*GetUserGameRecordResp_UserGameRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{20, 0}
}

func (m *GetUserGameRecordResp_UserGameRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGameRecordResp_UserGameRecord.Unmarshal(m, b)
}
func (m *GetUserGameRecordResp_UserGameRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGameRecordResp_UserGameRecord.Marshal(b, m, deterministic)
}
func (m *GetUserGameRecordResp_UserGameRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGameRecordResp_UserGameRecord.Merge(m, src)
}
func (m *GetUserGameRecordResp_UserGameRecord) XXX_Size() int {
	return xxx_messageInfo_GetUserGameRecordResp_UserGameRecord.Size(m)
}
func (m *GetUserGameRecordResp_UserGameRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGameRecordResp_UserGameRecord.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGameRecordResp_UserGameRecord proto.InternalMessageInfo

func (m *GetUserGameRecordResp_UserGameRecord) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetUserGameRecordResp_UserGameRecord) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GetUserGameRecordResp_UserGameRecord) GetGameMode() int64 {
	if m != nil {
		return m.GameMode
	}
	return 0
}

func (m *GetUserGameRecordResp_UserGameRecord) GetWonTimes() int64 {
	if m != nil {
		return m.WonTimes
	}
	return 0
}

func (m *GetUserGameRecordResp_UserGameRecord) GetLoseTimes() int64 {
	if m != nil {
		return m.LoseTimes
	}
	return 0
}

type GetUserGameRecordResp_Data struct {
	UserGameRecord       *GetUserGameRecordResp_UserGameRecord `protobuf:"bytes,1,opt,name=user_game_record,json=userGameRecord,proto3" json:"user_game_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *GetUserGameRecordResp_Data) Reset()         { *m = GetUserGameRecordResp_Data{} }
func (m *GetUserGameRecordResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetUserGameRecordResp_Data) ProtoMessage()    {}
func (*GetUserGameRecordResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{20, 1}
}

func (m *GetUserGameRecordResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserGameRecordResp_Data.Unmarshal(m, b)
}
func (m *GetUserGameRecordResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserGameRecordResp_Data.Marshal(b, m, deterministic)
}
func (m *GetUserGameRecordResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserGameRecordResp_Data.Merge(m, src)
}
func (m *GetUserGameRecordResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetUserGameRecordResp_Data.Size(m)
}
func (m *GetUserGameRecordResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserGameRecordResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserGameRecordResp_Data proto.InternalMessageInfo

func (m *GetUserGameRecordResp_Data) GetUserGameRecord() *GetUserGameRecordResp_UserGameRecord {
	if m != nil {
		return m.UserGameRecord
	}
	return nil
}

// 批量用户战绩查询
type MGetUserGameRecordReq struct {
	Uid                  []int64  `protobuf:"varint,1,rep,packed,name=uid,proto3" json:"uid,omitempty"`
	GameType             int64    `protobuf:"varint,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	GameMode             int64    `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	Begin                int64    `protobuf:"varint,4,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64    `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MGetUserGameRecordReq) Reset()         { *m = MGetUserGameRecordReq{} }
func (m *MGetUserGameRecordReq) String() string { return proto.CompactTextString(m) }
func (*MGetUserGameRecordReq) ProtoMessage()    {}
func (*MGetUserGameRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{21}
}

func (m *MGetUserGameRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MGetUserGameRecordReq.Unmarshal(m, b)
}
func (m *MGetUserGameRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MGetUserGameRecordReq.Marshal(b, m, deterministic)
}
func (m *MGetUserGameRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MGetUserGameRecordReq.Merge(m, src)
}
func (m *MGetUserGameRecordReq) XXX_Size() int {
	return xxx_messageInfo_MGetUserGameRecordReq.Size(m)
}
func (m *MGetUserGameRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MGetUserGameRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_MGetUserGameRecordReq proto.InternalMessageInfo

func (m *MGetUserGameRecordReq) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *MGetUserGameRecordReq) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *MGetUserGameRecordReq) GetGameMode() int64 {
	if m != nil {
		return m.GameMode
	}
	return 0
}

func (m *MGetUserGameRecordReq) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *MGetUserGameRecordReq) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type MGetUserGameRecordResp struct {
	DmError              int64                        `protobuf:"varint,1,opt,name=dm_error,json=dmError,proto3" json:"dm_error,omitempty"`
	ErrorMsg             string                       `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Data                 *MGetUserGameRecordResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MGetUserGameRecordResp) Reset()         { *m = MGetUserGameRecordResp{} }
func (m *MGetUserGameRecordResp) String() string { return proto.CompactTextString(m) }
func (*MGetUserGameRecordResp) ProtoMessage()    {}
func (*MGetUserGameRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{22}
}

func (m *MGetUserGameRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MGetUserGameRecordResp.Unmarshal(m, b)
}
func (m *MGetUserGameRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MGetUserGameRecordResp.Marshal(b, m, deterministic)
}
func (m *MGetUserGameRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MGetUserGameRecordResp.Merge(m, src)
}
func (m *MGetUserGameRecordResp) XXX_Size() int {
	return xxx_messageInfo_MGetUserGameRecordResp.Size(m)
}
func (m *MGetUserGameRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MGetUserGameRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_MGetUserGameRecordResp proto.InternalMessageInfo

func (m *MGetUserGameRecordResp) GetDmError() int64 {
	if m != nil {
		return m.DmError
	}
	return 0
}

func (m *MGetUserGameRecordResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *MGetUserGameRecordResp) GetData() *MGetUserGameRecordResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type MGetUserGameRecordResp_UserGameRecord struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameType             int64    `protobuf:"varint,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	GameMode             int64    `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	WonTimes             int64    `protobuf:"varint,4,opt,name=won_times,json=wonTimes,proto3" json:"won_times,omitempty"`
	LoseTimes            int64    `protobuf:"varint,5,opt,name=lose_times,json=loseTimes,proto3" json:"lose_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MGetUserGameRecordResp_UserGameRecord) Reset()         { *m = MGetUserGameRecordResp_UserGameRecord{} }
func (m *MGetUserGameRecordResp_UserGameRecord) String() string { return proto.CompactTextString(m) }
func (*MGetUserGameRecordResp_UserGameRecord) ProtoMessage()    {}
func (*MGetUserGameRecordResp_UserGameRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{22, 0}
}

func (m *MGetUserGameRecordResp_UserGameRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MGetUserGameRecordResp_UserGameRecord.Unmarshal(m, b)
}
func (m *MGetUserGameRecordResp_UserGameRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MGetUserGameRecordResp_UserGameRecord.Marshal(b, m, deterministic)
}
func (m *MGetUserGameRecordResp_UserGameRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MGetUserGameRecordResp_UserGameRecord.Merge(m, src)
}
func (m *MGetUserGameRecordResp_UserGameRecord) XXX_Size() int {
	return xxx_messageInfo_MGetUserGameRecordResp_UserGameRecord.Size(m)
}
func (m *MGetUserGameRecordResp_UserGameRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MGetUserGameRecordResp_UserGameRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MGetUserGameRecordResp_UserGameRecord proto.InternalMessageInfo

func (m *MGetUserGameRecordResp_UserGameRecord) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MGetUserGameRecordResp_UserGameRecord) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *MGetUserGameRecordResp_UserGameRecord) GetGameMode() int64 {
	if m != nil {
		return m.GameMode
	}
	return 0
}

func (m *MGetUserGameRecordResp_UserGameRecord) GetWonTimes() int64 {
	if m != nil {
		return m.WonTimes
	}
	return 0
}

func (m *MGetUserGameRecordResp_UserGameRecord) GetLoseTimes() int64 {
	if m != nil {
		return m.LoseTimes
	}
	return 0
}

type MGetUserGameRecordResp_Data struct {
	UserGameRecord       []*MGetUserGameRecordResp_UserGameRecord `protobuf:"bytes,1,rep,name=user_game_record,json=userGameRecord,proto3" json:"user_game_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *MGetUserGameRecordResp_Data) Reset()         { *m = MGetUserGameRecordResp_Data{} }
func (m *MGetUserGameRecordResp_Data) String() string { return proto.CompactTextString(m) }
func (*MGetUserGameRecordResp_Data) ProtoMessage()    {}
func (*MGetUserGameRecordResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_913b8b58ff514ee5, []int{22, 1}
}

func (m *MGetUserGameRecordResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MGetUserGameRecordResp_Data.Unmarshal(m, b)
}
func (m *MGetUserGameRecordResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MGetUserGameRecordResp_Data.Marshal(b, m, deterministic)
}
func (m *MGetUserGameRecordResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MGetUserGameRecordResp_Data.Merge(m, src)
}
func (m *MGetUserGameRecordResp_Data) XXX_Size() int {
	return xxx_messageInfo_MGetUserGameRecordResp_Data.Size(m)
}
func (m *MGetUserGameRecordResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_MGetUserGameRecordResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_MGetUserGameRecordResp_Data proto.InternalMessageInfo

func (m *MGetUserGameRecordResp_Data) GetUserGameRecord() []*MGetUserGameRecordResp_UserGameRecord {
	if m != nil {
		return m.UserGameRecord
	}
	return nil
}

func init() {
	proto.RegisterType((*InvitationEmptyResp)(nil), "game_center_base.InvitationEmptyResp")
	proto.RegisterType((*InvitationIdResp)(nil), "game_center_base.InvitationIdResp")
	proto.RegisterType((*InvitationIdResp_Data)(nil), "game_center_base.InvitationIdResp.Data")
	proto.RegisterType((*SetInvitationInfoReq)(nil), "game_center_base.SetInvitationInfoReq")
	proto.RegisterType((*InvitationIdReq)(nil), "game_center_base.InvitationIdReq")
	proto.RegisterType((*UidReq)(nil), "game_center_base.UidReq")
	proto.RegisterType((*DontDisturbStatus)(nil), "game_center_base.DontDisturbStatus")
	proto.RegisterType((*GetInvitationInfoResp)(nil), "game_center_base.GetInvitationInfoResp")
	proto.RegisterType((*InvitationInfoData)(nil), "game_center_base.InvitationInfoData")
	proto.RegisterType((*UserInfo)(nil), "game_center_base.UserInfo")
	proto.RegisterType((*GameInfo)(nil), "game_center_base.GameInfo")
	proto.RegisterType((*InvitationFreqSingleReq)(nil), "game_center_base.InvitationFreqSingleReq")
	proto.RegisterType((*InvitationFreqSingleResp)(nil), "game_center_base.InvitationFreqSingleResp")
	proto.RegisterType((*InvitationFreqSingleResp_Data)(nil), "game_center_base.InvitationFreqSingleResp.Data")
	proto.RegisterType((*SetContinuousRefusedReq)(nil), "game_center_base.SetContinuousRefusedReq")
	proto.RegisterType((*ContinuousRefusedResp)(nil), "game_center_base.ContinuousRefusedResp")
	proto.RegisterType((*ContinuousRefusedResp_Data)(nil), "game_center_base.ContinuousRefusedResp.Data")
	proto.RegisterType((*SetInvitationRoomIdReq)(nil), "game_center_base.SetInvitationRoomIdReq")
	proto.RegisterType((*UpdateUserGameRecordReq)(nil), "game_center_base.UpdateUserGameRecordReq")
	proto.RegisterType((*UpdateUserGameRecordResp)(nil), "game_center_base.UpdateUserGameRecordResp")
	proto.RegisterType((*BatchUpdateUserGameRecordReq)(nil), "game_center_base.BatchUpdateUserGameRecordReq")
	proto.RegisterType((*BatchUpdateUserGameRecordResp)(nil), "game_center_base.BatchUpdateUserGameRecordResp")
	proto.RegisterType((*GetUserGameRecordReq)(nil), "game_center_base.GetUserGameRecordReq")
	proto.RegisterType((*GetUserGameRecordResp)(nil), "game_center_base.GetUserGameRecordResp")
	proto.RegisterType((*GetUserGameRecordResp_UserGameRecord)(nil), "game_center_base.GetUserGameRecordResp.UserGameRecord")
	proto.RegisterType((*GetUserGameRecordResp_Data)(nil), "game_center_base.GetUserGameRecordResp.Data")
	proto.RegisterType((*MGetUserGameRecordReq)(nil), "game_center_base.MGetUserGameRecordReq")
	proto.RegisterType((*MGetUserGameRecordResp)(nil), "game_center_base.MGetUserGameRecordResp")
	proto.RegisterType((*MGetUserGameRecordResp_UserGameRecord)(nil), "game_center_base.MGetUserGameRecordResp.UserGameRecord")
	proto.RegisterType((*MGetUserGameRecordResp_Data)(nil), "game_center_base.MGetUserGameRecordResp.Data")
}

func init() { proto.RegisterFile("game.center.base.proto", fileDescriptor_913b8b58ff514ee5) }

var fileDescriptor_913b8b58ff514ee5 = []byte{
	// 1224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xd7, 0xda, 0xa9, 0x63, 0x1f, 0xa7, 0xf9, 0x27, 0xd3, 0x7c, 0xb8, 0xee, 0xbf, 0x50, 0xb6,
	0x1f, 0x71, 0x29, 0xb8, 0x52, 0x90, 0x28, 0x82, 0x1b, 0x82, 0x53, 0x42, 0x10, 0xe6, 0x62, 0x9d,
	0x00, 0x95, 0x40, 0xcb, 0x66, 0xf7, 0xc4, 0x19, 0xc8, 0xce, 0x38, 0xbb, 0xe3, 0xa4, 0x91, 0xb8,
	0x46, 0xa2, 0xdc, 0x23, 0xb8, 0xe7, 0x09, 0x10, 0x4f, 0xc0, 0x7b, 0x20, 0xf1, 0x28, 0x68, 0xc6,
	0x63, 0x7b, 0x37, 0x3b, 0x76, 0x16, 0x1c, 0x90, 0xb8, 0xf3, 0x39, 0xb3, 0x73, 0x3e, 0x7f, 0xe7,
	0xcc, 0x39, 0x86, 0xb5, 0xae, 0x17, 0x62, 0xd3, 0x47, 0x26, 0x30, 0x6a, 0x1e, 0x78, 0x31, 0x36,
	0x7b, 0x11, 0x17, 0x9c, 0x2c, 0x49, 0xbe, 0x3b, 0xe0, 0xbb, 0x92, 0x6f, 0xb7, 0xe1, 0xc6, 0x2e,
	0x3b, 0xa5, 0xc2, 0x13, 0x94, 0xb3, 0xa7, 0x61, 0x4f, 0x9c, 0x3b, 0x18, 0xf7, 0xc8, 0x4d, 0x28,
	0x07, 0xa1, 0x8b, 0x51, 0xc4, 0xa3, 0x9a, 0x75, 0xc7, 0x6a, 0x14, 0x9d, 0xf9, 0x20, 0x7c, 0x2a,
	0x49, 0x72, 0x0b, 0x2a, 0x8a, 0xef, 0x86, 0x71, 0xb7, 0x56, 0xb8, 0x63, 0x35, 0x2a, 0x4e, 0x59,
	0x31, 0xda, 0x71, 0xd7, 0xfe, 0xd5, 0x82, 0xa5, 0xb1, 0xbc, 0xdd, 0x60, 0x16, 0x61, 0xe4, 0x1d,
	0x98, 0x0b, 0x3c, 0xe1, 0xd5, 0x8a, 0x77, 0xac, 0x46, 0x75, 0x73, 0xa3, 0x79, 0xd1, 0xf8, 0xe6,
	0x45, 0x4d, 0xcd, 0x6d, 0x4f, 0x78, 0x8e, 0xba, 0x54, 0x7f, 0x04, 0x73, 0x92, 0x22, 0x77, 0xe1,
	0x3a, 0x1d, 0x7d, 0xe6, 0xd2, 0x40, 0x59, 0x50, 0x71, 0x16, 0x68, 0xe2, 0xae, 0xfd, 0x8b, 0x05,
	0x2b, 0x1d, 0x14, 0x09, 0x79, 0xec, 0x90, 0x3b, 0x78, 0x42, 0x96, 0xa0, 0xd8, 0xd7, 0x77, 0x8a,
	0x8e, 0xfc, 0x49, 0x6e, 0x03, 0x08, 0x2f, 0xea, 0xa2, 0x70, 0xe5, 0x41, 0x41, 0x1d, 0x54, 0x06,
	0x9c, 0x7d, 0x1a, 0x48, 0x87, 0x94, 0x99, 0xe2, 0xbc, 0x87, 0xca, 0xf0, 0xa2, 0x53, 0x96, 0x8c,
	0xbd, 0xf3, 0x1e, 0x8e, 0x0e, 0x43, 0x1e, 0x60, 0x6d, 0x6e, 0x7c, 0xd8, 0xe6, 0x01, 0x92, 0x35,
	0x28, 0xc5, 0xbc, 0x1f, 0xf9, 0x58, 0xbb, 0xa6, 0x4e, 0x34, 0x45, 0xd6, 0x61, 0x3e, 0xe2, 0x3c,
	0x94, 0xa6, 0x97, 0x94, 0xe9, 0x25, 0x49, 0xee, 0x06, 0xf6, 0x07, 0xf0, 0xbf, 0x74, 0x00, 0x4c,
	0xe6, 0x66, 0xdc, 0x2f, 0x18, 0xdc, 0xaf, 0x43, 0x69, 0x9f, 0x9a, 0x05, 0xd8, 0x8f, 0x60, 0x79,
	0x9b, 0x33, 0xb1, 0x4d, 0x63, 0xd1, 0x8f, 0x0e, 0x3a, 0xc2, 0x13, 0xfd, 0x58, 0xd9, 0xaa, 0x7e,
	0xe9, 0x2f, 0x35, 0x65, 0x7f, 0x67, 0xc1, 0xea, 0x4e, 0x36, 0x8e, 0x33, 0x60, 0xe0, 0xad, 0x14,
	0x06, 0xee, 0x4d, 0xc5, 0x00, 0x3b, 0xe4, 0x63, 0x00, 0xd8, 0x2f, 0x0a, 0x40, 0xb2, 0x87, 0xb9,
	0xf0, 0xa0, 0xfc, 0x43, 0x16, 0x60, 0xa4, 0x13, 0xac, 0x29, 0x52, 0x83, 0xf9, 0x08, 0x7d, 0xa4,
	0xa7, 0xc3, 0xdc, 0x0e, 0x49, 0xf2, 0x44, 0xa7, 0x96, 0xb2, 0x43, 0xae, 0x52, 0x5b, 0xdd, 0xac,
	0x67, 0x8d, 0xdd, 0xf1, 0x42, 0x54, 0x21, 0x51, 0x69, 0x97, 0xbf, 0xa4, 0xf7, 0x7e, 0x84, 0x9e,
	0x40, 0xd7, 0x13, 0x3a, 0xf3, 0xe5, 0x01, 0x63, 0x4b, 0x24, 0xe2, 0x5c, 0x4a, 0xc6, 0x39, 0x89,
	0x89, 0xf9, 0x24, 0x26, 0x12, 0x20, 0x2a, 0x27, 0x41, 0x64, 0xbf, 0x0d, 0xe5, 0xfd, 0x18, 0x23,
	0xa5, 0x91, 0xc0, 0x1c, 0xa3, 0xfe, 0xd7, 0xda, 0x71, 0xf5, 0x9b, 0xd4, 0xa1, 0xdc, 0xe3, 0x91,
	0x88, 0x3c, 0x2a, 0x86, 0x29, 0x18, 0xd2, 0xf6, 0xcf, 0x16, 0x94, 0x77, 0x12, 0xe6, 0x2a, 0xaf,
	0x98, 0x17, 0xa2, 0x96, 0xa0, 0x7c, 0xf9, 0xd8, 0x0b, 0x91, 0xdc, 0x83, 0xc5, 0x11, 0xbe, 0x5d,
	0x81, 0xcf, 0x87, 0xb2, 0x16, 0x86, 0x20, 0xdf, 0xc3, 0xe7, 0x62, 0x86, 0x12, 0x19, 0x1e, 0x52,
	0x9f, 0x33, 0x15, 0x2b, 0xad, 0x7c, 0xd7, 0xe7, 0xcc, 0xfe, 0x10, 0xd6, 0xc7, 0xe9, 0x7e, 0x3f,
	0xc2, 0x93, 0x0e, 0x65, 0xdd, 0x63, 0xfc, 0x3b, 0x55, 0x6c, 0xff, 0x6e, 0x41, 0xcd, 0x2c, 0x6c,
	0x06, 0x28, 0xb7, 0x52, 0x50, 0x7e, 0x3c, 0x0d, 0xca, 0x69, 0x8d, 0xc9, 0xb6, 0xb6, 0xad, 0xdb,
	0xda, 0x7d, 0x58, 0x8c, 0x30, 0xf4, 0x28, 0xa3, 0xac, 0xeb, 0x0a, 0xaa, 0x93, 0x51, 0x74, 0xae,
	0x8f, 0xb8, 0x7b, 0x34, 0x44, 0xb2, 0x0a, 0x25, 0x1a, 0xbb, 0xbe, 0xc7, 0x94, 0x35, 0x65, 0xe7,
	0x1a, 0x8d, 0x5b, 0x1e, 0xb3, 0x5b, 0xb0, 0xde, 0x41, 0xd1, 0xe2, 0x4c, 0x50, 0xd6, 0xe7, 0xfd,
	0xd8, 0xc1, 0xc3, 0x7e, 0x8c, 0x13, 0x5a, 0xc8, 0x18, 0x84, 0x85, 0x54, 0xb1, 0xff, 0x66, 0xc1,
	0xaa, 0x41, 0xc4, 0x0c, 0x11, 0x7a, 0x37, 0x15, 0xa1, 0xd7, 0xb2, 0x11, 0x32, 0xaa, 0x4b, 0x86,
	0xe7, 0xb1, 0x0e, 0xcf, 0x06, 0x2c, 0xd1, 0xd8, 0x8d, 0x8f, 0xf8, 0x99, 0x1b, 0x70, 0x26, 0xdc,
	0x80, 0x0e, 0x5b, 0xd5, 0x75, 0x1a, 0x77, 0x8e, 0xf8, 0x99, 0xee, 0x69, 0xf6, 0x27, 0xb0, 0x96,
	0x6a, 0xfc, 0x8e, 0xaa, 0x23, 0x19, 0x88, 0x5c, 0x8d, 0x22, 0x51, 0x88, 0x85, 0x54, 0x73, 0xfe,
	0xd6, 0x82, 0xf5, 0xfd, 0x5e, 0xe0, 0x09, 0x94, 0x75, 0x27, 0xcb, 0xc7, 0x41, 0x9f, 0x47, 0x13,
	0x42, 0x9c, 0x2a, 0x89, 0xc2, 0xb4, 0x92, 0x28, 0x5e, 0x28, 0x89, 0x97, 0xa1, 0xaa, 0x0e, 0x23,
	0x8c, 0xfb, 0xc7, 0x42, 0x57, 0x0c, 0x74, 0x95, 0x3e, 0xc9, 0xb1, 0x1d, 0xa8, 0x99, 0xed, 0x98,
	0xe1, 0x95, 0x3f, 0x86, 0xff, 0xbf, 0xe7, 0x09, 0xff, 0x68, 0x92, 0x83, 0x1f, 0xc1, 0x82, 0x36,
	0x4a, 0x72, 0x64, 0xe4, 0x8b, 0x8d, 0xea, 0xe6, 0xc3, 0x6c, 0x3e, 0x27, 0x08, 0x70, 0xaa, 0xdd,
	0x11, 0x19, 0xdb, 0x9f, 0xc2, 0xed, 0x29, 0xda, 0x66, 0x70, 0xe3, 0x85, 0x05, 0x2b, 0x3b, 0x28,
	0xfe, 0xd9, 0x04, 0xad, 0xc0, 0xb5, 0x03, 0xec, 0x52, 0xa6, 0x53, 0x33, 0x20, 0xa4, 0x06, 0x64,
	0x81, 0xee, 0xf7, 0xf2, 0xa7, 0xfd, 0x43, 0x51, 0x3d, 0x9d, 0x57, 0xe7, 0xde, 0xe5, 0xd5, 0x64,
	0x54, 0x97, 0xac, 0xa6, 0x1f, 0x2d, 0x58, 0x4c, 0x7f, 0x71, 0xa5, 0xa1, 0xb9, 0x05, 0x95, 0x33,
	0xce, 0x54, 0xf7, 0x8a, 0x87, 0xbd, 0xfe, 0x8c, 0x33, 0xd9, 0xb8, 0x62, 0xd9, 0xa1, 0x8f, 0x79,
	0x8c, 0xfa, 0x74, 0x10, 0xa8, 0x8a, 0xe4, 0xa8, 0xe3, 0xfa, 0x91, 0x2e, 0xf4, 0x2f, 0x61, 0xa9,
	0x1f, 0x63, 0xe4, 0x26, 0xf0, 0xa6, 0x8c, 0xab, 0x6e, 0xbe, 0x99, 0xd7, 0xe1, 0x0b, 0xac, 0xc5,
	0x7e, 0x8a, 0xb6, 0xbf, 0xb7, 0x60, 0xb5, 0x3d, 0x1d, 0x26, 0xc5, 0x7f, 0x0f, 0x26, 0x3f, 0x15,
	0x61, 0xad, 0x7d, 0xb5, 0x38, 0xd9, 0x4a, 0xe1, 0xe4, 0xf5, 0x6c, 0xd8, 0xda, 0xff, 0x65, 0xa0,
	0x50, 0x0d, 0x14, 0xcf, 0x08, 0x14, 0xd9, 0x97, 0x9e, 0xe4, 0xf6, 0x78, 0x3a, 0x52, 0x36, 0xff,
	0x58, 0x80, 0x65, 0x49, 0xb6, 0x94, 0xa4, 0x0e, 0x46, 0xa7, 0xd4, 0x47, 0xf2, 0x0c, 0x6e, 0xa6,
	0x46, 0xe2, 0x8e, 0x1a, 0x25, 0xf5, 0x20, 0x5d, 0x33, 0xf4, 0x44, 0x35, 0x89, 0xd7, 0xed, 0xcb,
	0xd7, 0x1d, 0xe2, 0xc2, 0x72, 0x66, 0x6b, 0x21, 0x0f, 0xb2, 0x17, 0x4d, 0xab, 0x4d, 0x5e, 0x05,
	0x99, 0x71, 0x9e, 0xbc, 0x72, 0xd9, 0xc5, 0x93, 0xfa, 0x86, 0xb1, 0xf6, 0x0c, 0x6b, 0xc1, 0xe7,
	0xc9, 0x75, 0x71, 0xcb, 0xf7, 0xb1, 0x27, 0xf2, 0xc8, 0xbf, 0x3f, 0xed, 0x93, 0xf1, 0x16, 0x9b,
	0x92, 0xde, 0xf2, 0x98, 0x8f, 0xc7, 0x57, 0x28, 0xfd, 0x0b, 0x58, 0x4e, 0xcc, 0x0d, 0x83, 0x79,
	0xe4, 0x0a, 0xc5, 0x7f, 0x06, 0xab, 0x63, 0x76, 0x62, 0x05, 0x9b, 0x82, 0x99, 0x9c, 0x92, 0x5d,
	0x78, 0x29, 0x95, 0x8d, 0xec, 0x7e, 0x37, 0x59, 0xc5, 0xdd, 0xec, 0x49, 0xf6, 0xfa, 0x57, 0x6a,
	0x9b, 0xce, 0x0c, 0x6b, 0xe4, 0xa1, 0x11, 0x9a, 0xa6, 0x31, 0xd4, 0x84, 0x20, 0xf3, 0xac, 0xf9,
	0x4c, 0xbd, 0xe1, 0x59, 0x5d, 0x93, 0x5d, 0xc8, 0x2d, 0xfa, 0x10, 0x6e, 0x18, 0x66, 0x43, 0xd2,
	0xb8, 0xa4, 0xc0, 0x46, 0x23, 0x64, 0xde, 0x7c, 0x84, 0xb0, 0x62, 0x1a, 0xfd, 0x4d, 0xe1, 0x9a,
	0xb0, 0xe1, 0xd4, 0x5f, 0xcd, 0xbf, 0x4d, 0x48, 0x75, 0xa6, 0x51, 0x8a, 0xe4, 0x9f, 0xcf, 0x4c,
	0xea, 0x26, 0x4e, 0x67, 0xdf, 0xc0, 0xcd, 0x89, 0xe3, 0x1b, 0x69, 0x66, 0x05, 0x4d, 0x9b, 0x2c,
	0xeb, 0x8f, 0xff, 0xd2, 0xf7, 0x71, 0x8f, 0x04, 0xaa, 0x83, 0x5d, 0xd0, 0xfa, 0x20, 0xd7, 0x68,
	0x30, 0xa9, 0x8d, 0x19, 0xb4, 0x74, 0x81, 0x64, 0x9f, 0x0c, 0xb2, 0x91, 0xef, 0x61, 0x39, 0xa9,
	0x37, 0xf2, 0xbe, 0x40, 0x07, 0x25, 0xf5, 0x3f, 0xde, 0x1b, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0xe4, 0x44, 0x19, 0xe1, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GameCenterService service

type GameCenterService interface {
	GetInvitationSenderStatus(ctx context.Context, in *UidReq, opts ...client.CallOption) (*InvitationIdResp, error)
	SetInvitationInfo(ctx context.Context, in *SetInvitationInfoReq, opts ...client.CallOption) (*InvitationIdResp, error)
	GetInvitationInfo(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*GetInvitationInfoResp, error)
	InvitationAccept(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error)
	InvitationCancel(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error)
	InvitationRefused(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error)
	InvitationDontDisturb(ctx context.Context, in *UidReq, opts ...client.CallOption) (*InvitationEmptyResp, error)
	GetInvitationDontDisturbStatus(ctx context.Context, in *UidReq, opts ...client.CallOption) (*DontDisturbStatus, error)
	SetContinuousRefused(ctx context.Context, in *SetContinuousRefusedReq, opts ...client.CallOption) (*ContinuousRefusedResp, error)
	GetContinuousRefused(ctx context.Context, in *UidReq, opts ...client.CallOption) (*ContinuousRefusedResp, error)
	SetInvitationRoomId(ctx context.Context, in *SetInvitationRoomIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error)
	InvitationFreqSingle(ctx context.Context, in *InvitationFreqSingleReq, opts ...client.CallOption) (*InvitationFreqSingleResp, error)
	UpdateUserGameRecord(ctx context.Context, in *UpdateUserGameRecordReq, opts ...client.CallOption) (*UpdateUserGameRecordResp, error)
	BatchUpdateUserGameRecord(ctx context.Context, in *BatchUpdateUserGameRecordReq, opts ...client.CallOption) (*BatchUpdateUserGameRecordResp, error)
	GetUserGameRecord(ctx context.Context, in *GetUserGameRecordReq, opts ...client.CallOption) (*GetUserGameRecordResp, error)
	MGetUserGameRecord(ctx context.Context, in *MGetUserGameRecordReq, opts ...client.CallOption) (*MGetUserGameRecordResp, error)
}

type gameCenterService struct {
	clients map[string]client.Client
}

func NewGameCenterService(c client.Factory) GameCenterService {
	if c == nil {
		panic("factory is nil")
	}
	service := &gameCenterService{
		clients: make(map[string]client.Client),
	}
	service.clients["game_center_base.GameCenterService.GetInvitationSenderStatus"] = c.Client("game_center_base.GameCenterService.GetInvitationSenderStatus")
	service.clients["game_center_base.GameCenterService.SetInvitationInfo"] = c.Client("game_center_base.GameCenterService.SetInvitationInfo")
	service.clients["game_center_base.GameCenterService.GetInvitationInfo"] = c.Client("game_center_base.GameCenterService.GetInvitationInfo")
	service.clients["game_center_base.GameCenterService.InvitationAccept"] = c.Client("game_center_base.GameCenterService.InvitationAccept")
	service.clients["game_center_base.GameCenterService.InvitationCancel"] = c.Client("game_center_base.GameCenterService.InvitationCancel")
	service.clients["game_center_base.GameCenterService.InvitationRefused"] = c.Client("game_center_base.GameCenterService.InvitationRefused")
	service.clients["game_center_base.GameCenterService.InvitationDontDisturb"] = c.Client("game_center_base.GameCenterService.InvitationDontDisturb")
	service.clients["game_center_base.GameCenterService.GetInvitationDontDisturbStatus"] = c.Client("game_center_base.GameCenterService.GetInvitationDontDisturbStatus")
	service.clients["game_center_base.GameCenterService.SetContinuousRefused"] = c.Client("game_center_base.GameCenterService.SetContinuousRefused")
	service.clients["game_center_base.GameCenterService.GetContinuousRefused"] = c.Client("game_center_base.GameCenterService.GetContinuousRefused")
	service.clients["game_center_base.GameCenterService.SetInvitationRoomId"] = c.Client("game_center_base.GameCenterService.SetInvitationRoomId")
	service.clients["game_center_base.GameCenterService.InvitationFreqSingle"] = c.Client("game_center_base.GameCenterService.InvitationFreqSingle")
	service.clients["game_center_base.GameCenterService.UpdateUserGameRecord"] = c.Client("game_center_base.GameCenterService.UpdateUserGameRecord")
	service.clients["game_center_base.GameCenterService.BatchUpdateUserGameRecord"] = c.Client("game_center_base.GameCenterService.BatchUpdateUserGameRecord")
	service.clients["game_center_base.GameCenterService.GetUserGameRecord"] = c.Client("game_center_base.GameCenterService.GetUserGameRecord")
	service.clients["game_center_base.GameCenterService.MGetUserGameRecord"] = c.Client("game_center_base.GameCenterService.MGetUserGameRecord")
	return service
}

func NewGameCenterServiceName(name string) GameCenterService {
	service := &gameCenterService{
		clients: make(map[string]client.Client),
	}
	service.clients["game_center_base.GameCenterService.GetInvitationSenderStatus"] = proxy.InitRPC(name, "game_center_base.GameCenterService.GetInvitationSenderStatus")
	service.clients["game_center_base.GameCenterService.SetInvitationInfo"] = proxy.InitRPC(name, "game_center_base.GameCenterService.SetInvitationInfo")
	service.clients["game_center_base.GameCenterService.GetInvitationInfo"] = proxy.InitRPC(name, "game_center_base.GameCenterService.GetInvitationInfo")
	service.clients["game_center_base.GameCenterService.InvitationAccept"] = proxy.InitRPC(name, "game_center_base.GameCenterService.InvitationAccept")
	service.clients["game_center_base.GameCenterService.InvitationCancel"] = proxy.InitRPC(name, "game_center_base.GameCenterService.InvitationCancel")
	service.clients["game_center_base.GameCenterService.InvitationRefused"] = proxy.InitRPC(name, "game_center_base.GameCenterService.InvitationRefused")
	service.clients["game_center_base.GameCenterService.InvitationDontDisturb"] = proxy.InitRPC(name, "game_center_base.GameCenterService.InvitationDontDisturb")
	service.clients["game_center_base.GameCenterService.GetInvitationDontDisturbStatus"] = proxy.InitRPC(name, "game_center_base.GameCenterService.GetInvitationDontDisturbStatus")
	service.clients["game_center_base.GameCenterService.SetContinuousRefused"] = proxy.InitRPC(name, "game_center_base.GameCenterService.SetContinuousRefused")
	service.clients["game_center_base.GameCenterService.GetContinuousRefused"] = proxy.InitRPC(name, "game_center_base.GameCenterService.GetContinuousRefused")
	service.clients["game_center_base.GameCenterService.SetInvitationRoomId"] = proxy.InitRPC(name, "game_center_base.GameCenterService.SetInvitationRoomId")
	service.clients["game_center_base.GameCenterService.InvitationFreqSingle"] = proxy.InitRPC(name, "game_center_base.GameCenterService.InvitationFreqSingle")
	service.clients["game_center_base.GameCenterService.UpdateUserGameRecord"] = proxy.InitRPC(name, "game_center_base.GameCenterService.UpdateUserGameRecord")
	service.clients["game_center_base.GameCenterService.BatchUpdateUserGameRecord"] = proxy.InitRPC(name, "game_center_base.GameCenterService.BatchUpdateUserGameRecord")
	service.clients["game_center_base.GameCenterService.GetUserGameRecord"] = proxy.InitRPC(name, "game_center_base.GameCenterService.GetUserGameRecord")
	service.clients["game_center_base.GameCenterService.MGetUserGameRecord"] = proxy.InitRPC(name, "game_center_base.GameCenterService.MGetUserGameRecord")
	return service
}

func (c *gameCenterService) GetInvitationSenderStatus(ctx context.Context, in *UidReq, opts ...client.CallOption) (*InvitationIdResp, error) {
	out := new(InvitationIdResp)
	err := c.clients["game_center_base.GameCenterService.GetInvitationSenderStatus"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) SetInvitationInfo(ctx context.Context, in *SetInvitationInfoReq, opts ...client.CallOption) (*InvitationIdResp, error) {
	out := new(InvitationIdResp)
	err := c.clients["game_center_base.GameCenterService.SetInvitationInfo"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) GetInvitationInfo(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*GetInvitationInfoResp, error) {
	out := new(GetInvitationInfoResp)
	err := c.clients["game_center_base.GameCenterService.GetInvitationInfo"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) InvitationAccept(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error) {
	out := new(InvitationEmptyResp)
	err := c.clients["game_center_base.GameCenterService.InvitationAccept"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) InvitationCancel(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error) {
	out := new(InvitationEmptyResp)
	err := c.clients["game_center_base.GameCenterService.InvitationCancel"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) InvitationRefused(ctx context.Context, in *InvitationIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error) {
	out := new(InvitationEmptyResp)
	err := c.clients["game_center_base.GameCenterService.InvitationRefused"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) InvitationDontDisturb(ctx context.Context, in *UidReq, opts ...client.CallOption) (*InvitationEmptyResp, error) {
	out := new(InvitationEmptyResp)
	err := c.clients["game_center_base.GameCenterService.InvitationDontDisturb"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) GetInvitationDontDisturbStatus(ctx context.Context, in *UidReq, opts ...client.CallOption) (*DontDisturbStatus, error) {
	out := new(DontDisturbStatus)
	err := c.clients["game_center_base.GameCenterService.GetInvitationDontDisturbStatus"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) SetContinuousRefused(ctx context.Context, in *SetContinuousRefusedReq, opts ...client.CallOption) (*ContinuousRefusedResp, error) {
	out := new(ContinuousRefusedResp)
	err := c.clients["game_center_base.GameCenterService.SetContinuousRefused"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) GetContinuousRefused(ctx context.Context, in *UidReq, opts ...client.CallOption) (*ContinuousRefusedResp, error) {
	out := new(ContinuousRefusedResp)
	err := c.clients["game_center_base.GameCenterService.GetContinuousRefused"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) SetInvitationRoomId(ctx context.Context, in *SetInvitationRoomIdReq, opts ...client.CallOption) (*InvitationEmptyResp, error) {
	out := new(InvitationEmptyResp)
	err := c.clients["game_center_base.GameCenterService.SetInvitationRoomId"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) InvitationFreqSingle(ctx context.Context, in *InvitationFreqSingleReq, opts ...client.CallOption) (*InvitationFreqSingleResp, error) {
	out := new(InvitationFreqSingleResp)
	err := c.clients["game_center_base.GameCenterService.InvitationFreqSingle"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) UpdateUserGameRecord(ctx context.Context, in *UpdateUserGameRecordReq, opts ...client.CallOption) (*UpdateUserGameRecordResp, error) {
	out := new(UpdateUserGameRecordResp)
	err := c.clients["game_center_base.GameCenterService.UpdateUserGameRecord"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) BatchUpdateUserGameRecord(ctx context.Context, in *BatchUpdateUserGameRecordReq, opts ...client.CallOption) (*BatchUpdateUserGameRecordResp, error) {
	out := new(BatchUpdateUserGameRecordResp)
	err := c.clients["game_center_base.GameCenterService.BatchUpdateUserGameRecord"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) GetUserGameRecord(ctx context.Context, in *GetUserGameRecordReq, opts ...client.CallOption) (*GetUserGameRecordResp, error) {
	out := new(GetUserGameRecordResp)
	err := c.clients["game_center_base.GameCenterService.GetUserGameRecord"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCenterService) MGetUserGameRecord(ctx context.Context, in *MGetUserGameRecordReq, opts ...client.CallOption) (*MGetUserGameRecordResp, error) {
	out := new(MGetUserGameRecordResp)
	err := c.clients["game_center_base.GameCenterService.MGetUserGameRecord"].Invoke(ctx, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameCenterService service

type GameCenterServiceHandler interface {
	GetInvitationSenderStatus(context.Context, *UidReq) (*InvitationIdResp, error)
	SetInvitationInfo(context.Context, *SetInvitationInfoReq) (*InvitationIdResp, error)
	GetInvitationInfo(context.Context, *InvitationIdReq) (*GetInvitationInfoResp, error)
	InvitationAccept(context.Context, *InvitationIdReq) (*InvitationEmptyResp, error)
	InvitationCancel(context.Context, *InvitationIdReq) (*InvitationEmptyResp, error)
	InvitationRefused(context.Context, *InvitationIdReq) (*InvitationEmptyResp, error)
	InvitationDontDisturb(context.Context, *UidReq) (*InvitationEmptyResp, error)
	GetInvitationDontDisturbStatus(context.Context, *UidReq) (*DontDisturbStatus, error)
	SetContinuousRefused(context.Context, *SetContinuousRefusedReq) (*ContinuousRefusedResp, error)
	GetContinuousRefused(context.Context, *UidReq) (*ContinuousRefusedResp, error)
	SetInvitationRoomId(context.Context, *SetInvitationRoomIdReq) (*InvitationEmptyResp, error)
	InvitationFreqSingle(context.Context, *InvitationFreqSingleReq) (*InvitationFreqSingleResp, error)
	UpdateUserGameRecord(context.Context, *UpdateUserGameRecordReq) (*UpdateUserGameRecordResp, error)
	BatchUpdateUserGameRecord(context.Context, *BatchUpdateUserGameRecordReq) (*BatchUpdateUserGameRecordResp, error)
	GetUserGameRecord(context.Context, *GetUserGameRecordReq) (*GetUserGameRecordResp, error)
	MGetUserGameRecord(context.Context, *MGetUserGameRecordReq) (*MGetUserGameRecordResp, error)
}

func RegisterGameCenterServiceHandler(s server.Server, hdlr GameCenterServiceHandler, opts ...server.HandlerOption) {
	type gameCenterService interface {
		GetInvitationSenderStatus(ctx context.Context, in *UidReq) (*InvitationIdResp, error)
		SetInvitationInfo(ctx context.Context, in *SetInvitationInfoReq) (*InvitationIdResp, error)
		GetInvitationInfo(ctx context.Context, in *InvitationIdReq) (*GetInvitationInfoResp, error)
		InvitationAccept(ctx context.Context, in *InvitationIdReq) (*InvitationEmptyResp, error)
		InvitationCancel(ctx context.Context, in *InvitationIdReq) (*InvitationEmptyResp, error)
		InvitationRefused(ctx context.Context, in *InvitationIdReq) (*InvitationEmptyResp, error)
		InvitationDontDisturb(ctx context.Context, in *UidReq) (*InvitationEmptyResp, error)
		GetInvitationDontDisturbStatus(ctx context.Context, in *UidReq) (*DontDisturbStatus, error)
		SetContinuousRefused(ctx context.Context, in *SetContinuousRefusedReq) (*ContinuousRefusedResp, error)
		GetContinuousRefused(ctx context.Context, in *UidReq) (*ContinuousRefusedResp, error)
		SetInvitationRoomId(ctx context.Context, in *SetInvitationRoomIdReq) (*InvitationEmptyResp, error)
		InvitationFreqSingle(ctx context.Context, in *InvitationFreqSingleReq) (*InvitationFreqSingleResp, error)
		UpdateUserGameRecord(ctx context.Context, in *UpdateUserGameRecordReq) (*UpdateUserGameRecordResp, error)
		BatchUpdateUserGameRecord(ctx context.Context, in *BatchUpdateUserGameRecordReq) (*BatchUpdateUserGameRecordResp, error)
		GetUserGameRecord(ctx context.Context, in *GetUserGameRecordReq) (*GetUserGameRecordResp, error)
		MGetUserGameRecord(ctx context.Context, in *MGetUserGameRecordReq) (*MGetUserGameRecordResp, error)
	}
	type GameCenterService struct {
		gameCenterService
	}
	opts = append(opts, server.HandlerName("game_center_base.GameCenterService"))
	h := &gameCenterServiceHandler{hdlr}
	if err := s.Handle(s.NewHandler(&GameCenterService{h}, opts...)); err != nil {
		panic(err)
	}
}

type gameCenterServiceHandler struct {
	GameCenterServiceHandler
}

func (h *gameCenterServiceHandler) GetInvitationSenderStatus(ctx context.Context, in *UidReq) (*InvitationIdResp, error) {
	return h.GameCenterServiceHandler.GetInvitationSenderStatus(ctx, in)
}

func (h *gameCenterServiceHandler) SetInvitationInfo(ctx context.Context, in *SetInvitationInfoReq) (*InvitationIdResp, error) {
	return h.GameCenterServiceHandler.SetInvitationInfo(ctx, in)
}

func (h *gameCenterServiceHandler) GetInvitationInfo(ctx context.Context, in *InvitationIdReq) (*GetInvitationInfoResp, error) {
	return h.GameCenterServiceHandler.GetInvitationInfo(ctx, in)
}

func (h *gameCenterServiceHandler) InvitationAccept(ctx context.Context, in *InvitationIdReq) (*InvitationEmptyResp, error) {
	return h.GameCenterServiceHandler.InvitationAccept(ctx, in)
}

func (h *gameCenterServiceHandler) InvitationCancel(ctx context.Context, in *InvitationIdReq) (*InvitationEmptyResp, error) {
	return h.GameCenterServiceHandler.InvitationCancel(ctx, in)
}

func (h *gameCenterServiceHandler) InvitationRefused(ctx context.Context, in *InvitationIdReq) (*InvitationEmptyResp, error) {
	return h.GameCenterServiceHandler.InvitationRefused(ctx, in)
}

func (h *gameCenterServiceHandler) InvitationDontDisturb(ctx context.Context, in *UidReq) (*InvitationEmptyResp, error) {
	return h.GameCenterServiceHandler.InvitationDontDisturb(ctx, in)
}

func (h *gameCenterServiceHandler) GetInvitationDontDisturbStatus(ctx context.Context, in *UidReq) (*DontDisturbStatus, error) {
	return h.GameCenterServiceHandler.GetInvitationDontDisturbStatus(ctx, in)
}

func (h *gameCenterServiceHandler) SetContinuousRefused(ctx context.Context, in *SetContinuousRefusedReq) (*ContinuousRefusedResp, error) {
	return h.GameCenterServiceHandler.SetContinuousRefused(ctx, in)
}

func (h *gameCenterServiceHandler) GetContinuousRefused(ctx context.Context, in *UidReq) (*ContinuousRefusedResp, error) {
	return h.GameCenterServiceHandler.GetContinuousRefused(ctx, in)
}

func (h *gameCenterServiceHandler) SetInvitationRoomId(ctx context.Context, in *SetInvitationRoomIdReq) (*InvitationEmptyResp, error) {
	return h.GameCenterServiceHandler.SetInvitationRoomId(ctx, in)
}

func (h *gameCenterServiceHandler) InvitationFreqSingle(ctx context.Context, in *InvitationFreqSingleReq) (*InvitationFreqSingleResp, error) {
	return h.GameCenterServiceHandler.InvitationFreqSingle(ctx, in)
}

func (h *gameCenterServiceHandler) UpdateUserGameRecord(ctx context.Context, in *UpdateUserGameRecordReq) (*UpdateUserGameRecordResp, error) {
	return h.GameCenterServiceHandler.UpdateUserGameRecord(ctx, in)
}

func (h *gameCenterServiceHandler) BatchUpdateUserGameRecord(ctx context.Context, in *BatchUpdateUserGameRecordReq) (*BatchUpdateUserGameRecordResp, error) {
	return h.GameCenterServiceHandler.BatchUpdateUserGameRecord(ctx, in)
}

func (h *gameCenterServiceHandler) GetUserGameRecord(ctx context.Context, in *GetUserGameRecordReq) (*GetUserGameRecordResp, error) {
	return h.GameCenterServiceHandler.GetUserGameRecord(ctx, in)
}

func (h *gameCenterServiceHandler) MGetUserGameRecord(ctx context.Context, in *MGetUserGameRecordReq) (*MGetUserGameRecordResp, error) {
	return h.GameCenterServiceHandler.MGetUserGameRecord(ctx, in)
}
